### ISSUE TITLE
Simulator endpoint abstraction

### ISSUE THREAD

**Issue by mbrobbel** [mbrobbel/dqcsim-rs#27]
At some point we may want to support plugins connecting to a simulator via TCP instead of IPC. Instead of using a `String` to communicate the simulator's address, we have to wrap the address in an `Endpoint` structure, which plugins can use to select the different types of supported channels.

**Comment by jvanstraten** [comment]
Internally, sure. But user-facing a URL should be used to not overcomplicate things. I'm surprised that the IPC crate docs don't seem to specify what its address strings look like, but assuming they're filesystem paths to named pipes (and not already URLs) the URLs could look like

 - `ipc:<path to pipe>`
 - `tcp://x.x.x.x:x/`

https://docs.rs/url to parse.

**Comment by mbrobbel** [comment]
https://xkcd.com/1691/
