### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by jvanstraten** [mbrobbel/dqcsim-rs#36]
Do we want some kind of code coverage tool to guide writing tests or is that a lot of work to set up? It would be nice to have something like it for making sure all the possible branches in the gatestream protocol due to desynchronization are covered. Looks like most rust-specific coverage tools are dead with bugs, but kcov looks promising. Having said that, I have never done code coverage stuff in any serious way, so...

**Comment by mbrobbel** [comment]
I'll work on this.

**Comment by mbrobbel** [comment]
Before:
https://codecov.io/gh/mbrobbel/dqcsim-rs/src/d3cdf349f039e8db246ebc9334ef637128a9eb48/dqcsim/src/plugin/state.rs#L668

Add test:
https://github.com/mbrobbel/dqcsim-rs/pull/37/commits/e6f4d1700670ba6d4eef689c83ebe91b84edce6e#diff-c97869907924fce0bc799e8e4180201eR160

After:
https://codecov.io/gh/mbrobbel/dqcsim-rs/src/e6f4d1700670ba6d4eef689c83ebe91b84edce6e/dqcsim/src/plugin/state.rs#L668
