### ISSUE TITLE
Missing symlinks for dqcs[fe|op|be]py in wheel

### ISSUE THREAD

**Issue by jvanstraten** [mbrobbel/dqcsim-rs#83]
`dqcsim hello.py null` doesn't work because `dqcsfepy` is missing. Likewise for the other plugin types. It should be a symlink to python, preferably the interpreter used to install the wheel with.

Matthijs, can you look at this? Since you have more experience with the wheel stuff. If a symlink is not possible, I guess this would also work:

```sh
#!/bin/sh
python3 "$@"
```

**Comment by mbrobbel** [comment]
Closed by #84.
